version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command : symfony serve 
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=dev
    depends_on:
      - db
  db:
    image: mysql:8.0.32
    environment:
      - MYSQL_DATABASE=PsychoAuthDB
      - MYSQL_PASSWORD=root@Saif123
      - MYSQL_ROOT_PASSWORD=root@Saif123
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:

  










 